name: TownyWaypoints
version: '1.0'
main: net.mvndicraft.townywaypoints.TownyWaypoints
description: Configurable Waypoints as Towny plots
api-version: '1.20'
folia-supported: true
dependencies:
  server:
    Towny:
      load: BEFORE
      required: true
    Vault:
      load: BEFORE
      required: true